### ISSUE TITLE
How to change message 重播 to Replay when the video ended . Thanks

### ISSUE THREAD

**Issue by MrVlad001** [renzifeng/ZFPlayer#363]
How to change message 重播 to Replay when the video ended . Thanks
![unnamed](https://user-images.githubusercontent.com/5904699/35007644-9e0ce586-fafa-11e7-9db0-60479d6df517.jpg)

**Comment by michaelwestbrooksii** [comment]
Hey! Had a problem with this as well. Learned that this was actually an image. So you have to go into the bundle resource and change the image.

**Comment by ibhavin** [comment]
If you have installed `ZFPlayer` from cocoapods then find replay image from:
`Pods > Pods > ZFPlayer > Resources > ZFPlayer.bundle > ZFPlayer_repeat_video.png, @2x, @3x`
delete those images and replace with this images ( images will not display here properly because it is transparent and white color):

![zfplayer_repeat_video](https://user-images.githubusercontent.com/16459948/35136650-c4e017d4-fd0a-11e7-9e77-f4cf310bc09d.png)
![zfplayer_repeat_video 2x](https://user-images.githubusercontent.com/16459948/35136657-c8c88c50-fd0a-11e7-9992-90c5e649caf7.png)
![zfplayer_repeat_video 3x](https://user-images.githubusercontent.com/16459948/35136658-cc2751ba-fd0a-11e7-8d17-6ab5fabe6ab7.png)

**Comment by MrVlad001** [comment]
@michaelwestbrooksii @ibhavin thanks guys 😄
