### ISSUE TITLE
AVPlayer播放缓冲一段时间后断网

### ISSUE THREAD

**Issue by sunqiming** [renzifeng/ZFPlayer#531]
明明还有很长一段缓冲完了,但是无法播放
画面不动了

**Comment by ArchForge** [comment]
I think this is a relatively common issue when playing on low bandwidth.
https://forums.developer.apple.com/thread/31215

I would guess that some videos/streams where there's no option to lower the video quality, the player first switches to audio only and then just stops when it can't load fast enough. Maybe it could be fixed by adjusting the buffering settings based on available bandwidth.
